### ISSUE TITLE
Баг с сейфом

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/dayzmta#3]
Нельзя взаимодействовать с сейфом, который установлен в контейнере. 
![mta-screen_2017-09-02_23-44-36](https://user-images.githubusercontent.com/31574768/29998644-6a861c2c-9039-11e7-8a0c-9b1ce84df698.png)

**Comment by salwador** [comment]
Fix in r341

**Comment by salwador** [comment]
Поскольку с новой версии r++ счётчика не будет, фикс будет в версии от 1.2.27
